### ISSUE TITLE
New Error: Can't login with my account on euw

### ISSUE THREAD

**Issue by ghost** [3SUM/cactus#7]
Hey there!
First of all thank you for giving us such a nice piece of software to learn something from!
I can't login with Turbo and Sniper mode on EUW. 
![Unbenannt](https://user-images.githubusercontent.com/57769962/153032910-7dc09eea-b79a-4c6c-9dcd-f00426f98d6c.PNG)
I've also tried it on Termux (a mobile version of cmd). It gives me the same Error but with a bit of context there.
It seems like the auth site of Riot Games denies the access.
[response.txt](https://github.com/3SUM/cactus/files/8025852/response.txt)

![Unbenannt1](https://user-images.githubusercontent.com/57769962/153035805-9087372a-2a11-42b2-8a0c-e45c7f0f60ca.PNG)

I quickly looked up what error 1020 means. It means that the cookies are not enabled.

Thanks!
Steffen

**Comment by derekackworth** [comment]
Same issue here for NA
![Capture](https://user-images.githubusercontent.com/14387819/153541617-eb9fed82-9418-4579-a5fd-0d54a14205ae.PNG)

**Comment by giorgi-o** [comment]
Btw, error 1020 is a result of Riot cracking down on account checkers.
See https://github.com/giorgi-o/SkinPeek/issues/4#issuecomment-1022316597
Unless someone is willing to implement a bypass, there isn't much the typical end user can do.
